### ISSUE TITLE
[Lock Pos / Rot] feature of Physics Gun in Garry's mod

### ISSUE THREAD

**Issue by lsy1304** [JusMahBASSCannon/KKRagdollRevamp#6]
**Is your request something completely new (a Feature) or a change to an existing feature to make it work better (a Quality of Life fix)?**
It would be better to add feature like [Lock Pos / Rot] in Physics Gun in Garry's mod

**Explain your idea!**
[drag ragdoll] feature is also brilliant feature, but i want to [Lock Pos / Rot value]

**How would this benefit you if implemented?**
it is make so much variant ways about enjoying with studio!!

**Comment by lsy1304** [comment]
i found this is already in Todo list.

**Comment by JusMahBASSCannon** [comment]
> i found this is already in Todo list.

Hi, yes! I plan on including this in an upcoming version and I've already gotten started with it. Thank you for the request!

Because this is already included in my feature todos, I will mark this as closed.
